easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Comic
        - App\Entity\Comment
        - App\Entity\User
        - App\Entity\Persona
        - App\Entity\Background
