easy_admin:
    entities:
        # List the entity class name you want to manage
        Comic:
            class: App\Entity\Comic
        Comment:
            class: App\Entity\Comment
        User:
            class: App\Entity\User
        Persona:
            class: App\Entity\Persona
            edit:
                fields:
                    - name
                    - path
                    - category
                    - public
                    - { property: 'birthday', type_options: { widget: 'single_text' } }
                    - job
                    - alias
                    - nationality
                    - description
                    - biography
                    - friends
        Background:
            class: App\Entity\Background

    formats:
        date: 'd/m/Y'