version: '3'
services:
  apache:
    build: .docker/apache
    container_name: bz_apache
    ports:
      - 80:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/boommz
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php

  mysql:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: bz_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: boommz
      MYSQL_USER: boommz
      MYSQL_PASSWORD: password

  php:
    build: .docker/php
    container_name: bz_php
    volumes:
      - .:/home/wwwroot/boommz
    environment:
      - maildev_host=bz_maildev
    depends_on:
      - maildev
      - mysql
    links:
      - mysql:mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bz_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: bz_maildev
    ports:
      - 8001:80